name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Repositoryni klonlash
      - name: Checkout repository
        uses: actions/checkout@v3

      # Node.js o‘rnatish
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'pnpm'

      # Serverga ulanish uchun SSH sozlash
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

      # Serverga loyihani yuborish
      - name: Deploy to server
        run: |
          rsync -avz --delete dist/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/path/to/your/project
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
            cd /path/to/your/project &&
            pnpm install --prod &&
            pm2 restart arendum-api
          "
